### PR TITLE
Code to plot movie ratings versus time for visualization

### PR DESCRIPTION
**Pull request by abhishek078**
Code to plot movie ratings versus time for visualization for a specific movie "Tiger Zinda Hai".

### CODE REVIEW

**Comment by abhishek078** [comment]
@aribis369 please review the pull request.

**Comment by aribis369** [comment]
@abhishek078 Very impressive work. Nice to see that you have worked on your own model. Please make a new folder "visualization" to store graph plotting programs. But for the tweet scrapper part please add a snippet to store inside mogodb or csv or dataframe etc
.

**Comment by abhishek078** [comment]
@aribis369 please review the pull request.

**Comment by aribis369** [comment]
@abhishek078 Really nice work. Appreciate your contributions.

**Comment by aribis369** [comment]
@abhishek078 I'm merging this PR but can you please plot graphs for 7-10 days for different movies. We can show it in our README.

**Pull request merged**
